config/routes.rb
Rails.application.routes.draw do

  resources :relate_rewards, only: [:create]

  resources :boards

  devise_ios_rails_for :agents
  devise_ios_rails_for :merchant_users  

  resources :sms_tokens, only: [:create]
  resources :pension, only: [:index]
  
  resources :jajin, only: [:index]
  
  resources :merchants, only: [:index, :show, :update, :create] do
    resources :shops, only: [:index, :new, :create, :update]
    collection do
      get 'customer_index'
    end
    member do
      post 'add_tag'
      get 'get_followers'
      post 'follow'
      post 'unfollow'
      post 'like'
      post 'unlike'
      post 'member_cards'
    end
  end

  resource :merchant, only: [:show] 

  match 'merchant/:id/merchant_customer/verify' => 'merchant_customers#verify', :via => [:post]

  resources :shops, only: [:index, :show] do
    member do
      post 'follow'
      post 'unfollow'
    end
    collection do
      post 'neighbour_shop' 
    end
  end

  resources :member_cards, only: [:index, :show] do
    collection do
      post 'check_member_card'
      post 'bind'
    end
    member do
      post 'unbind'
    end
  end
  
  resources :yl_trades, only: [:create, :index, :show]
  resources :merchant_messages, only: [:create, :index] do
    member do
      post 'like'
      post 'unlike'
    end
  end
  resources :merchant_giving_logs, only: [:index, :show]

  resources :bank_cards, only: [:index, :create] do
    collection do
      post 'send_msg'
      get 'bank_info'
      post 'verify'
    end
  end

  resource :merchant_sys_reg_info

  devise_ios_rails_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :customer_reg_infos, only: [:show] do
    collection do
      get 'verify_state'
    end
  end
  resource :customer_reg_info, only: [:show, :update], :via => :options

  resources :identity_verifies, only: [:create, :update, :index]

  resource :check_user, only: [:show] do
    member do
      post 'reset'
      post 'device'
    end
  end

  resources :gain_accounts, only: [:index, :show] do
    resources :gain_histories, only: [:index, :show]
  end

  resources :pension_logs, only: [:index]

  resources :jajin_logs, only: [:index, :show]

  resources :given_logs, only: [:create]

  resources :reward_logs, only: [:create] do
    collection do
      post 'verify'
    end
  end

  resources :jajin_verify_logs, only: [:new, :create] do
    collection do
      post 'verify'
    end
  end

  resources :exchange_logs, only: [:create]

  resources :tl_trades, only: [:create]
  resources :lakala_trades, only: [:create]

  resources :consume_messages, only: [:show]
  
  resources :member_card_point_log, only: [:create, :show, :index]
  resource :verify, only: [:show]

  resources :topics, only: [:create, :show, :index] do
    member do
      post 'add_merchant'
      post 'add_tag'
    end
  end

  resources :tickets, only: [:create]

  resources :jajin_identity_code, only: [:create]
  
  resource :check_merchant do
    member do
      post 'reset'
    end
  end

  resource :check_agent do
    member do
      post 'reset'
    end
  end

  resource :agent do
    member do
      post 'update'
    end
  end

  resources :balance_logs, only: [:create, :index]

  resources :banks, only: [:index]

  resources :bank_card_types, only: [:index]
  
  get 'code' => 'jajin_verify_logs#new'
  get 'reward/:verify_code' => 'reward_logs#new'
  
  post 'point_log' => 'member_card_point_log#verify'

  root 'admin/home#index'
  namespace :admin do
    root 'home#index'

    devise_for :agent, :controllers => { 
      :sessions => 'admin/login/sessions' 
    }
    resources :agents do
      collection do
        post 'import'
        get 'logs'
      end
      member do
        get 'upload'
        get 'log'
        get 'down'
      end
    end

    resources :member_card_point_log do
      member do
      end
    end
  end

end

app/models/tl_trade.rb
# == Schema Information
#
# Table name: tl_trades
#
#  id             :integer          not null, primary key
#  phone          :string(255)
#  card           :string(255)
#  price          :float(24)
#  pos_ind        :string(255)
#  shop_ind       :string(255)
#  trade_ind      :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  customer_id    :integer
#  merchant_id    :integer
#  trade_time     :string(255)
#  pos_machine_id :integer
#  shop_id        :integer
#

class TlTrade < ActiveRecord::Base

  belongs_to :customer
  belongs_to :merchant
  belongs_to :shop
  belongs_to :pos_machine
  has_one :jajin_log, as: :jajinable

  validates_presence_of :customer, on: :create
  # validates_presence_of :merchant, on: :create

  before_validation :check_user, on: :create, if: "customer.nil?"
  before_validation :check_pos_machine, on: :create
  validate :must_have_jajin, on: :create
  validate :must_have_merchant, on: :create
  validates :phone, length: { is: 11 }

  after_create :calculate
  after_create :add_jajin_log

  after_create :add_jajin_identity_code

  scope :sum_day_price, -> { where("created_at > ?", Time.zone.now - 1.day).sum(:price) }
  scope :sum_week_price, -> { where("created_at > ?", Time.zone.now - 1.week).sum(:price) }
  scope :sum_month_price, -> { where("created_at > ?", Time.zone.now - 1.month).sum(:price) }
  scope :all_price, -> { all.sum(:price) }

  scope :day_price_merchant, -> { where("created_at > ?", Time.zone.now - 1.day).group(:merchant_id).pluck(:merchant_id) }
  scope :week_price_merchant, -> { where("created_at > ?", Time.zone.now - 1.week).group(:merchant_id).pluck(:merchant_id) }
  scope :month_price_merchant, -> { where("created_at > ?", Time.zone.now - 1.month).group(:merchant_id).pluck(:merchant_id) }
  scope :all_price_merchant, -> { all.group(:merchant_id).pluck(:merchant_id) }

  def as_json(options=nil)
    {
      phone: phone,
      card: card,
      price: price,
      trade_time: trade_time,
      pos_ind: pos_ind,
      shop_ind: shop_ind,
      trade_ind: trade_ind,
      customer_id: customer_id
    }
  end

  def company
    "刷卡返金"
  end

  private

  def check_user
    user = User.find_or_create_by_phone phone
    self.customer = user.customer
  end

  def check_pos_machine
    unique_ind = shop_ind+pos_ind
    pos_machine = PosMachine.find_by(pos_ind: unique_ind)
    if pos_machine.nil?
      pos_machine = PosMachine.create pos_ind: unique_ind
    end
    
    self.pos_machine = pos_machine
    self.shop = pos_machine.shop
    self.merchant_id = pos_machine.try(:shop).try(:merchant).try(:id) || 4
  end

  def must_have_jajin
    if self.customer.try(:jajin).blank?
      errors.add(:message, "小确幸账号不存在")
    end
  end

  def must_have_merchant
    # if self.try(:merchant).blank?
    #   errors.add(:message, "商户不存在")
    # end
  end

  def calculate
    jajin = self.customer.jajin
    ratio = merchant.try(:ratio) || 0.01
    amount = (price * 100 * ratio).ceil
    jajin.got += amount
    jajin.save!
  end

  def add_jajin_log
    ratio = merchant.try(:ratio) || 0.01
    amount = (price * 100 * ratio).ceil
    self.create_jajin_log customer: customer, amount: amount, merchant_id: merchant_id
  end

  def add_jajin_identity_code
    if phone.blank?
      JajinIdentityCode.create amount: price, trade_time: trade_time, verify_state: "unverified", verify_code: trade_ind, merchant_id: 4
    end
  end

end

app/controllers/tl_trades_controller.rb
class TlTradesController < ApplicationController
  before_action :set_tl_trade, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @tl_trades = TlTrade.all
    respond_with(@tl_trades)
  end

  def show
    respond_with(@tl_trade)
  end

  def new
    @tl_trade = TlTrade.new
    respond_with(@tl_trade)
  end

  def edit
  end

  def create
    @tl_trade = TlTrade.new(tl_trade_params)
    # @tl_trade.merchant_id = 4
    @tl_trade.save
    respond_with(@tl_trade)
  end

  def update
    @tl_trade.update(tl_trade_params)
    respond_with(@tl_trade)
  end

  def destroy
    @tl_trade.destroy
    respond_with(@tl_trade)
  end

  private
    def set_tl_trade
      @tl_trade = TlTrade.find(params[:id])
    end

    def tl_trade_params
      params.require(:tl_trade).permit(:phone, :card, :price, :trade_time, :pos_ind, :shop_ind, :trade_ind, :merchant_id)
    end
end

app/helpers/tl_trades_helper.rb
module TlTradesHelper
end

app/views/tl_trades/_form.html.erb
<%= form_for(@tl_trade) do |f| %>
  <% if @tl_trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tl_trade.errors.count, "error") %> prohibited this tl_trade from being saved:</h2>

      <ul>
      <% @tl_trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :card %><br>
    <%= f.text_field :card %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :trade_time %><br>
    <%= f.datetime_select :trade_time %>
  </div>
  <div class="field">
    <%= f.label :pos_ind %><br>
    <%= f.text_field :pos_ind %>
  </div>
  <div class="field">
    <%= f.label :shop_ind %><br>
    <%= f.text_field :shop_ind %>
  </div>
  <div class="field">
    <%= f.label :trade_ind %><br>
    <%= f.text_field :trade_ind %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tl_trades/edit.html.erb
<h1>Editing tl_trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @tl_trade %> |
<%= link_to 'Back', tl_trades_path %>

app/views/tl_trades/index.html.erb
<h1>Listing tl_trades</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Card</th>
      <th>Price</th>
      <th>Trade time</th>
      <th>Pos ind</th>
      <th>Shop ind</th>
      <th>Trade ind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tl_trades.each do |tl_trade| %>
      <tr>
        <td><%= tl_trade.phone %></td>
        <td><%= tl_trade.card %></td>
        <td><%= tl_trade.price %></td>
        <td><%= tl_trade.trade_time %></td>
        <td><%= tl_trade.pos_ind %></td>
        <td><%= tl_trade.shop_ind %></td>
        <td><%= tl_trade.trade_ind %></td>
        <td><%= link_to 'Show', tl_trade %></td>
        <td><%= link_to 'Edit', edit_tl_trade_path(tl_trade) %></td>
        <td><%= link_to 'Destroy', tl_trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tl trade', new_tl_trade_path %>

app/views/tl_trades/new.html.erb
<h1>New tl_trade</h1>

<%= render 'form' %>

<%= link_to 'Back', tl_trades_path %>

app/views/tl_trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @tl_trade.phone %>
</p>

<p>
  <strong>Card:</strong>
  <%= @tl_trade.card %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tl_trade.price %>
</p>

<p>
  <strong>Trade time:</strong>
  <%= @tl_trade.trade_time %>
</p>

<p>
  <strong>Pos ind:</strong>
  <%= @tl_trade.pos_ind %>
</p>

<p>
  <strong>Shop ind:</strong>
  <%= @tl_trade.shop_ind %>
</p>

<p>
  <strong>Trade ind:</strong>
  <%= @tl_trade.trade_ind %>
</p>

<%= link_to 'Edit', edit_tl_trade_path(@tl_trade) %> |
<%= link_to 'Back', tl_trades_path %>